# Generated by Django 2.2.19 on 2023-02-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name social network')),
                ('url', models.URLField(max_length=500, verbose_name='image url')),
            ],
        ),
    ]
