# Generated by Django 2.2.19 on 2023-02-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetwork',
            name='url_image',
            field=models.URLField(default='#', max_length=500, verbose_name='image url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='url',
            field=models.URLField(max_length=500, verbose_name='url social network'),
        ),
    ]
